services:
  app:
    build: .
    container_name: rine-print-manager
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - APP_NAME=${APP_NAME}
      - INVOICE_BASE_URL=${INVOICE_BASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - RINE_MOCK_PRINTERS=0
      - DEBUG=${DEBUG:-false}
    ports:
      - "8000:8000"
    volumes:
      - ./domain:/app/domain
      - ./application:/app/application
      - ./infrastructure:/app/infrastructure
      - ./workers:/app/workers
      - ./.data:/app/.data
      - /var/run/cups:/var/run/cups
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

  status-worker:
    build:
      context: .
      dockerfile: Dockerfile.status
    container_name: rine-status-worker
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - APP_NAME=${APP_NAME}
      - INVOICE_BASE_URL=${INVOICE_BASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - RINE_MOCK_PRINTERS=0
      - DEBUG=${DEBUG:-false}
    volumes:
      - ./domain:/app/domain
      - ./application:/app/application
      - ./infrastructure:/app/infrastructure
      - ./workers:/app/workers
      - ./.data:/app/.data
      - /var/run/cups:/var/run/cups
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

  print-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: rine-print-worker
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - APP_NAME=${APP_NAME}
      - INVOICE_BASE_URL=${INVOICE_BASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - RINE_MOCK_PRINTERS=0
      - DEBUG=${DEBUG:-false}
    volumes:
      - ./domain:/app/domain
      - ./application:/app/application
      - ./infrastructure:/app/infrastructure
      - ./workers:/app/workers
      - ./.data:/app/.data
      - /var/run/cups:/var/run/cups
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

  test:
    build:
      context: .
      target: test
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=${DATABASE_URL_TEST}
      - LOG_LEVEL=DEBUG
      - RINE_MOCK_PRINTERS=1
    volumes:
      - ./domain:/app/domain
      - ./application:/app/application
      - ./infrastructure:/app/infrastructure
      - ./workers:/app/workers
      - ./tests:/app/tests
      - ./.data:/app/.data
    profiles:
      - test
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
