services:
  app:
    build: .
    container_name: rine-print-manager
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./domain:/app/domain
      - ./application:/app/application
      - ./infrastructure:/app/infrastructure
      - ./infrastructure/templates:/app/templates
      - ./alembic.ini:/app/alembic.ini
      - ./.data:/app/.data
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn infrastructure.presentation.main:app --host 0.0.0.0 --port 8000
      "
    restart: always
